name: scanner_lib_android
description: Flutter implementation for Google Mobile Vision. Scan Barcodes, Recognize Text and Detect Faces.
version: 0.1.3
author: Eduardo Folly <edufolly@gmail.com>
homepage: https://github.com/edufolly/flutter_mobile_vision

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.github.edufolly.fluttermobilevision
    pluginClass: FlutterMobileVisionPlugin

environment:
  sdk: ">=2.0.0-a <3.0.0"
